### ISSUE TITLE
Usage of deprecated API

### ISSUE THREAD

**Issue by Cousken** [saif-ellafi/foundryvtt-minimal-ui#103]
Hello!

After upgrading to latest Foundry i get a warning from Minimal UI about usage of deprecated APIs

minmalui.js:703 (game.system.**data.**name)

```
commons.js:1256 Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1245:19)
    at get data [as data] (commons.js:11265:7)
    at Object.fn (minimalui.js:703:37)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at PlayerList._render (foundry.js:5071:13)
logCompatibilityWarning @ commons.js:1256
```

I also get an error here
```
foundry.js:691 Foundry VTT | Error thrown in hooked function '' for hook 'rtcSettingsChanged'
#call @ foundry.js:691
foundry.js:711 TypeError: Cannot read properties of undefined (reading 'Vw2dJYzSA2RtAZK8')
[Detected 1 package: minimal-ui]
    at Object.fn (minimalui.js:1015:27)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at AVSettings._onSettingsChanged (foundry.js:76900:11)
    at commons.js:1317:18
onError @ foundry.js:711
```

**Comment by aedgaruk** [comment]
As described above re: BasePackage#data ... and also a warning re: BasePackage#name

![image](https://user-images.githubusercontent.com/111492074/194969472-bc2985c3-6660-4d02-83fb-17417bafdd91.png)

**Comment by saif-ellafi** [comment]
Thank you, will be fixed in next release.
