### ISSUE TITLE
Console Error when launching Foundry

### ISSUE THREAD

**Issue by Noshei** [saif-ellafi/foundryvtt-minimal-ui#33]
I'm getting the following error from minimal UI when launching foundry.

`minimalui.js:1184 Uncaught (in promise) DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at Function.fixMinimizedRule (https://assets.forge-vtt.com/bazaar/modules/minimal-ui/0.8.8/minimalui.js:1184:31)
    at https://assets.forge-vtt.com/bazaar/modules/minimal-ui/0.8.8/minimalui.js:1382:43
    at Hooks._call#hook=ready (https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.5.2.0/lib-wrapper.js:1:27835)
    at Function._call (https://noshei.forge-vtt.com/scripts/foundry.js:2496:14)
    at C.🎁call_wrapped [as call_wrapped] (https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.5.2.0/lib-wrapper.js:1:11063)
    at Function.🎁Hooks._call#lib-wrapper (https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.5.2.0/lib-wrapper.js:1:27932)
    at Function.🎁Hooks._call#0 (https://assets.forge-vtt.com/bazaar/modules/lib-wrapper/1.5.2.0/lib-wrapper.js:1:7818)
    at Function.callAll (https://noshei.forge-vtt.com/scripts/foundry.js:2456:12)
    at Game.setupGame (https://noshei.forge-vtt.com/scripts/foundry.js:6560:11)
    at async Game._initializeGameView (https://noshei.forge-vtt.com/scripts/foundry.js:7319:5)`

**Comment by saif-ellafi** [comment]
Thanks! That's a nasty error.

If it's on launch right away, it probably means a conflict with something else?
If you can please help me with other modules you may have installed or any particular condition, like browser or system.

**Comment by saif-ellafi** [comment]
This could also be related with people using this module on the Forge. But I am almost certain that others use it in the Forge too.

**Comment by Noshei** [comment]
Chrome browser on windows 10.

Tested with only Minimal UI and dependents and still getting the same error

![image](https://user-images.githubusercontent.com/8866000/116416141-559c4f00-a7f7-11eb-8c78-59c09db91bdb.png)

**Comment by saif-ellafi** [comment]
That's unfortunate to hear. I'll have to ask for help into this, and why it doesn't happen to everyone.

**Comment by Noshei** [comment]
Seems like this is likely a forge related issue.  So I created a new world on both my forge server and my local test server, and only activated Minimal UI and dependents.  I only get the error on my forge server.  All version match between the servers.

**Comment by Noshei** [comment]
I'm not a JS guy, but I did a bit of digging and I believe I found the issue.  Its CORS security blocking access to cssRules because the css file is on a different sub domain from the request (assets.Forge-vtt.com vs noshei.forge-vtt.com).  Here is a post with a bit more detail, not sure how to fix this issue though.  This does confirm it is a forge related issue though.

https://stackoverflow.com/a/49994161

**Comment by saif-ellafi** [comment]
Thanks for the research. I pinged Forge's manager and he explicitly said this is not a CORS issue. Otherwise no other modules would work either.

I'll ask around other people using the forge to discard a special case, and think if there's any way of work around it.

**Comment by saif-ellafi** [comment]
I am working on this, got some solution in plan.

**Comment by saif-ellafi** [comment]
Fixed on 0.9.0!!! Please confirm :)

**Comment by Noshei** [comment]
Looks good, appears to be resolved.
